# Generated by Django 5.2.8 on 2025-11-26 13:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('document', '0001_initial'),
        ('product', '0001_initial'),
        ('warehouse', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='destination_warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='destination_documents', to='warehouse.warehouse', verbose_name='Склад-назначение'),
        ),
        migrations.AddField(
            model_name='document',
            name='source_warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='source_documents', to='warehouse.warehouse', verbose_name='Склад-источник'),
        ),
        migrations.AddField(
            model_name='documenthistory',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='document.document'),
        ),
        migrations.AddField(
            model_name='documenthistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='documentitem',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='document.document', verbose_name='Документ'),
        ),
        migrations.AddField(
            model_name='documentitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.product', verbose_name='Товар'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['document_type', 'status'], name='document_do_documen_033625_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['created_at'], name='document_do_created_778a6d_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['document_number'], name='document_do_documen_16da09_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='documentitem',
            unique_together={('document', 'product')},
        ),
    ]
