# Generated by Django 5.2.8 on 2025-11-26 08:33

import django.db.models.deletion
import marketplace.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marketplace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название маркетплейса')),
                ('code', models.CharField(choices=[('ozon', 'Ozon'), ('wildberries', 'Wildberries'), ('yandex_market', 'Yandex.Market')], max_length=50, verbose_name='Код')),
                ('status', models.CharField(choices=[('active', 'Активный'), ('inactive', 'Неактивный'), ('testing', 'Тестирование')], default='active', max_length=20, verbose_name='Статус')),
                ('environment', models.CharField(choices=[('production', 'Production'), ('sandbox', 'Sandbox')], default='production', max_length=20, verbose_name='Окружение')),
                ('api_key', marketplace.fields.EncryptedTextField(blank=True, verbose_name='API ключ')),
                ('client_id', models.CharField(blank=True, max_length=255, verbose_name='Client ID')),
                ('client_secret', marketplace.fields.EncryptedTextField(blank=True, verbose_name='Client Secret')),
                ('campaign_id', models.CharField(blank=True, max_length=255, verbose_name='ID кампании')),
                ('seller_id', models.CharField(blank=True, max_length=255, verbose_name='ID продавца')),
                ('warehouse_id', models.CharField(blank=True, max_length=255, verbose_name='ID склада')),
                ('extra_credentials', models.JSONField(blank=True, default=dict, verbose_name='Дополнительные учетные данные')),
                ('parsing_interval', models.PositiveIntegerField(default=30, verbose_name='Интервал парсинга (минуты)')),
                ('max_orders_per_request', models.PositiveIntegerField(default=1000, verbose_name='Максимум заказов за запрос')),
                ('days_to_look_back', models.PositiveIntegerField(default=7, verbose_name='Дней для поиска заказов назад')),
                ('is_webhook_enabled', models.BooleanField(default=False, verbose_name='Вебхуки включены')),
                ('webhook_url', models.URLField(blank=True, verbose_name='URL для вебхуков')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('last_successful_sync', models.DateTimeField(blank=True, null=True, verbose_name='Последняя успешная синхронизация')),
            ],
            options={
                'verbose_name': 'Маркетплейс',
                'verbose_name_plural': 'Маркетплейсы',
                'db_table': 'marketplaces',
            },
        ),
        migrations.CreateModel(
            name='MarketplaceProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode', models.CharField(blank=True, help_text='Штрихкод для маркетплейса', max_length=70, null=True)),
                ('external_sku', models.CharField(blank=True, help_text='Артикул на маркетплейсе', max_length=100, null=True, verbose_name='Внешний артикул')),
                ('external_product_id', models.CharField(blank=True, help_text='Внутренний ID товара на маркетплейсе', max_length=100, null=True, verbose_name='ID товара на маркетплейсе')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена товара на маркетплейсе')),
                ('status', models.CharField(choices=[('DRAFT', 'Черновик'), ('MODERATION', 'На модерации'), ('REJECTED', 'Отклонен'), ('ACTIVE', 'Активный'), ('INACTIVE', 'Неактивный'), ('ARCHIVED', 'В архиве')], default='DRAFT', max_length=20, verbose_name='Статус')),
                ('last_sync', models.DateTimeField(blank=True, null=True, verbose_name='Последняя синхронизация')),
                ('sync_enabled', models.BooleanField(default=True, verbose_name='Синхронизация включена')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('marketplace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='marketplace.marketplace', verbose_name='Маркетплейс')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marketplace_products', to='product.product', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'Товар на маркетплейсе',
                'verbose_name_plural': 'Товары на маркетплейсах',
                'ordering': ['marketplace', 'product'],
                'unique_together': {('product', 'marketplace')},
            },
        ),
    ]
