# Generated by Django 5.2.8 on 2025-11-26 08:33

import django.core.validators
import django.db.models.deletion
import product.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Код страны')),
                ('name', models.CharField(max_length=100, verbose_name='Название страны')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
            ],
            options={
                'verbose_name': 'Страна',
                'verbose_name_plural': 'Страны',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProductDirection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Код направления')),
                ('name', models.CharField(max_length=100, verbose_name='Название направления')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
            ],
            options={
                'verbose_name': 'Направление продукта',
                'verbose_name_plural': 'Направления продуктов',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70, verbose_name='Имя товара')),
                ('main_img', models.ImageField(blank=True, null=True, upload_to=product.models.product_main_image_path, verbose_name='Основное изображение')),
                ('article', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='Артикул')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активный')),
                ('packing_length', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Длина упаковки (см)')),
                ('packing_width', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Ширина упаковки (см)')),
                ('packing_height', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Высота упаковки (см)')),
                ('packing_weight', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Вес упаковки (кг)')),
                ('notes', models.JSONField(blank=True, help_text='Ответы на частые вопросы покупателей и т.д.', null=True, verbose_name='Примечания и FAQ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='category.category', verbose_name='Категория')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='product.country', verbose_name='Страна производства')),
                ('direction', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='product.productdirection', verbose_name='Направление продукта')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=product.models.product_additional_images_path, verbose_name='Изображение')),
                ('alt_text', models.CharField(blank=True, help_text='Описание изображения для SEO', max_length=200, null=True, verbose_name='Альтернативный текст')),
                ('order', models.PositiveIntegerField(default=0, help_text='Порядок отображения (меньше - выше)', verbose_name='Порядок')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_images', to='product.product', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'Дополнительное изображение',
                'verbose_name_plural': 'Дополнительные изображения',
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
