# Generated by Django 5.2.8 on 2025-11-26 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_type',
            field=models.CharField(choices=[('FBS', 'FBS'), ('FBO', 'FBO')], default='FBS', max_length=10, verbose_name='Тип заказа'),
        ),
    ]
