# Generated by Django 5.2.8 on 2025-11-26 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('DIRECTOR', 'Руководитель'), ('SENIOR_MANAGER', 'Старший менеджер'), ('MANAGER', 'Менеджер'), ('WAREHOUSE_MANAGER', 'Заведующий складом'), ('WAREHOUSE_WORKER', 'Работник склада'), ('ORDER_PICKER', 'Сборщик заказов')], default='MANAGER', max_length=20, verbose_name='Роль в системе'),
        ),
    ]
