# Generated by Django 5.2.8 on 2025-11-26 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductStock',
        ),
    ]
