# Generated by Django 5.2.8 on 2025-11-26 10:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available_quantity', models.PositiveIntegerField(default=0, verbose_name='Доступный остаток')),
                ('reserved_wb', models.PositiveIntegerField(default=0, verbose_name='В резерве WB')),
                ('reserved_ozon', models.PositiveIntegerField(default=0, verbose_name='В резерве OZON')),
                ('reserved_yandex', models.PositiveIntegerField(default=0, verbose_name='В резерве Яндекс.Маркет')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stock', to='product.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Остаток товара',
                'verbose_name_plural': 'Остатки товаров',
                'ordering': ['-updated_at'],
            },
        ),
    ]
